# Generated by Django 4.2.2 on 2023-07-03 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cartitem',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='appusers.cartitem'),
        ),
    ]
