# Generated by Django 4.2.2 on 2023-07-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0005_anonymouscart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnonymousCart',
        ),
    ]
