# Generated by Django 4.2.2 on 2023-07-09 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('appusers', '0007_cart_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousCart',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sessions.session')),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='session_id',
        ),
    ]
