# Generated by Django 4.2.2 on 2023-07-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0008_anonymouscart_remove_cart_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetails',
            name='firstname',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='lastname',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='phone_number',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='zip_code',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='AnonymousCart',
        ),
    ]
